version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ttmp-dev-new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # prisma-migrate:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
    # environment:
    #   DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ttmp-dev-new  # Use the correct database URL
    # command: ["npx", "prisma", "migrate", "dev", "--name", "init" ]
    # depends_on:
    #   - postgres
    # Ensure that the migration service runs only once and then stops
    # entrypoint: ["sleep", "infinity"]

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
